name: Deploy on Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-funcapp-reusable.yml
    with:
      function_app_name: functionapp-0194
      resource_group: test-rg
      working_directory: AzureFunctions
      app_version: ${{ github.event.release.tag_name }}
      set_app_setting: true
      use_publish_profile: true
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}