name: PR Quality (Reusable)

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: "20"

permissions:
  contents: read

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Commitlint (PR commits)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          BASE="${{ github.event.pull_request.base.sha }}"
          HEAD="${{ github.event.pull_request.head.sha }}"
          npx commitlint --from "$BASE" --to "$HEAD"
      - name: Commitlint (push fallback)
        if: ${{ github.event_name != 'pull_request' }}
        run: npx commitlint --from HEAD~1 --to HEAD

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: ESLint (full repo)
        run: npx eslint . --max-warnings=0