name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/semantic-release-reusable.yml
    with:
      node-version: "20.x"
      working-directory: "AzureFunctions"